### PR TITLE
Update to nightly-2023-11-25

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by willcrichton** [comment]
Thanks for the PR. (Just curious, are you using rustc_plugin for something?)

I will handle bumping the nightly (see #16). I decided to delete the entire `places_conflict` module because the new `rustc_borrowck::consumers` module now provides the same functionality publicly: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_borrowck/consumers/fn.places_conflict.html

**Comment by willcrichton** [comment]
Sorry I let this drop, but I'll just add -- @bjorn3 don't worry about breaking Flowistry, I am very used to it breaking every time the compiler updates 🙃 a changelog is more than enough!

**Comment by bjorn3** [comment]
In this case it is a non-trivial change of the rustc_driver interface that I fear will break flowistry in a way that could potentially require a rustc change to fix it again. To be precise I want to get rid of the rustc_driver query interface.

**Comment by willcrichton** [comment]
Got it. If you want to test anything, I just updated the dev branch of Flowistry to nightly-2024-01-06.

**Pull request closed without merging**
